before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        export MAKE=mingw32-make
        ;;
      *)
        export MAKE=make
        ;;
    esac
dist: focal
language: go
go:
- 1.15.x
script:
- $MAKE
branches:
  only:
  - master
  - "/v\\d+\\.\\d+\\.\\d+/"
matrix:
  include:
  - os: linux
  - os: osx
  - os: windows
before_deploy:
- $MAKE
deploy:
  provider: releases
  api_key:
    secure: ZSTQzFI9dUmxHxedbGyWZzTDFWlFV97fsHG5anVIi25YuPjgr+Qp7zWDkSi2ww5Nmuod58ieNB1sPPO5Fx2R3/FZ3Eq0gXO4wkqOFxf8GeCojNbQTzYHl6M5YPur/1vSPlpinQSVfs74G+OCQBLNZ5evgF1Y1scuX9ltBvTYmWBst/Ty5J7UVMhRf5cImHNHufob6nQhXv1tK51XFEAnX+2C+CNm/d9AgxeA7fo2NevqchwzsXU+5n6o29O4xI9rsSlslxUqmVbBaY/3+h0ZbBeWKY0RxBFyyhCsSJ7c29oJPjEpnr0U7g1frl2j8rBewHqbaqcMzfwCQZ277tU1dnvmzsXtggKy8NwjavUH3ekTh0fFasm9Xcwnfldsw7vihLk5pXNdKOM5cT4ylNeBMLHeapyr8LW3CV4zYYDN75GNxovOsA0kC0oWj63/QPVHhHWeIucYFEewNuW8DSwgDyFbAzVKwypU8EtQko0XDT1tnxlDdjq9BobmKxTC6udtJHbgx3juqBzIVxgUPljCoYmj+r75pNApSlQJr12LDpshArWjlj/RojLDjADz7dLeXWjsEi1PGK/jaqh7TQyayNN21aPcXdMOtW+jPD9JBzrmRJSalSbz25N/b25u1hPMyE6d5Y7eE+UW0D8iWY0aJAp2GNCxOKBg3LuivdJ4qsU=
  file_glob: true
  file: 'build/*'
  on:
    tags: true
    repo: kayrus/go-tun2socks
  skip_cleanup: 'true'
